#!/bin/bash

type="A"

type_check() {
  if [ "$type" != "A" ] && [ "$type" != "MX" ] && [ "$type" != "CNAME" ]; then
    echo "Enter a valid record (A,CNAME,MX)"
    exit 1
  fi
}

while getopts "t:" opt; do
  case $opt in
    t)
      type="$OPTARG"
      type_check
      ;;
    *)
      echo "Enter a valid record (A,CNAME,MX)"
      exit 1
      ;;
    esac
done

shift $((OPTIND-1))

name="$1"
ip_or_alias="$2"
domain="$3"

if [ "$type" == "A" ]; then
    echo "Adding A record"
    if [ "$#" -ne 3 ]; then
      echo "Needs 4 arguments"
      exit 1
    fi
    echo "$name"
    echo "$ip_or_alias"
    echo "$domain"
elif [ "$type" == "MX" ]; then
    echo "Adding MX record and A record"
    if [ "$#" -ne 3 ]; then
      echo "Needs 4 arguments"
      exit 1
    fi
    echo "$name"
    echo "$ip_or_alias"
    echo "$domain"
elif [ "$type" == "CNAME" ]; then
    echo "Adding CNAME record"
    if [ "$#" -ne 2 ]; then
      echo "Needs 3 arguments"
      exit 1
    fi
    echo "$name"
    echo "$ip_or_alias"
    echo "$domain"
fi
