#!/bin/sh

case "$1" in
    start)
	echo "Starting"

	iptables-restore < rules-ipv4
	ip6tables-restore < rules-ipv6

	echo "Started"
        ;;
    stop)
	echo "Stopping"

	iptables -F
	ip6tables -F

	iptables-restore < no-rules-ipv4
        ip6tables-restore < no-rules-ipv6

	echo "Stopped"
        ;;
    restart)
	echo "Restarting"

        $0 stop
        $0 start

	echo "Restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
