#!/bin/sh

case "$1" in
    start)
	echo "Starting"

	#Allow traffic originating from machine
	iptables -A OUTPUT -j ACCEPT

	#Allowing specified tcp ports to be accessed everywhere
	iptables -A INPUT -p tcp --dport 25 -j ACCEPT
	iptables -A INPUT -p tcp --dport 80 -j ACCEPT
	iptables -A INPUT -p tcp --dport 443 -j ACCEPT
	iptables -A INPUT -p tcp --dport 587 -j ACCEPT
	iptables -A INPUT -p tcp --dport 993 -j ACCEPT
	iptables -A INPUT -p tcp --dport 22345 -j ACCEPT

	# Allow incoming UDP and TCP traffic on port 53
	iptables -A INPUT -p udp --dport 53 -j ACCEPT
	iptables -A INPUT -p tcp --dport 53 -j ACCEPT

	# Allow ping from any host
	iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT

	# Allow all traffic from specified addresses
	iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
	iptables -A INPUT -s 192.168.255.0/24 -j ACCEPT
	iptables -A INPUT -s 172.16.0.0/16 -j ACCEPT

	iptables -A INPUT -s 193.191.177.12 -j ACCEPT
	iptables -A INPUT -s 193.191.177.1 -j ACCEPT

	echo "Started"
        ;;
    stop)
	echo "Stopping"

	#Remove current rules
	iptables -F

	echo "Stopped"
        ;;
    restart)
	echo "Restarting"

        $0 stop
        $0 start

	echo "Restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
